-- 이 시점(2026-09-28)까지 ddl-auto: update로 로컬에 쌓인 review_db 스키마를
-- 그대로 캡처한 baseline. Flyway 최초 도입 시 baseline-on-migrate로 처리되므로
-- 기존 데이터가 있는 환경에서는 이 파일이 실제로 실행되지 않고, 완전히 빈 DB에서만
-- 실행되어 스키마를 처음부터 만든다.

-- review
CREATE TABLE review (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    data_origin character varying(255),
    dataset_run_id bigint,
    deleted_at timestamp(6) with time zone,
    is_synthetic boolean NOT NULL,
    member_id bigint NOT NULL,
    product_id bigint NOT NULL,
    star_rate double precision NOT NULL,
    text character varying(255),
    usage_period integer NOT NULL,
    CONSTRAINT review_data_origin_check CHECK (data_origin IN ('REAL', 'SYNTHETIC')),
    CONSTRAINT uk_review_member_product UNIQUE (member_id, product_id)
);

-- review_pet (Review.pets @ElementCollection)
CREATE TABLE review_pet (
    review_id bigint NOT NULL,
    age integer NOT NULL,
    breed_id bigint NOT NULL,
    breed_size character varying(255),
    name character varying(255) NOT NULL,
    neutered boolean NOT NULL,
    pet_id bigint NOT NULL,
    sex character varying(255) NOT NULL,
    species character varying(255) NOT NULL,
    weight double precision NOT NULL,
    CONSTRAINT review_pet_breed_size_check CHECK (breed_size IN ('SMALL', 'MEDIUM', 'LARGE')),
    CONSTRAINT review_pet_sex_check CHECK (sex IN ('MALE', 'FEMALE')),
    CONSTRAINT review_pet_species_check CHECK (species IN ('DOG', 'CAT')),
    CONSTRAINT fkcl24m7cjrxmuy4oaldti7n8hx FOREIGN KEY (review_id) REFERENCES review(id)
);

-- review_health_concern (Review.petHealthConcernCodes @ElementCollection)
CREATE TABLE review_health_concern (
    review_id bigint NOT NULL,
    concern_code character varying(255),
    CONSTRAINT ukgmg9jbxsicx6xd926bgq4vb5m UNIQUE (review_id, concern_code),
    CONSTRAINT fkhn6lkoq8w0acn19r98uhwyonr FOREIGN KEY (review_id) REFERENCES review(id)
);

-- review_image
CREATE TABLE review_image (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url character varying(255) NOT NULL,
    review_id bigint NOT NULL,
    sort_order integer NOT NULL
);

-- review_question
CREATE TABLE review_question (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_answer character varying(255),
    review_id bigint NOT NULL,
    review_question_type character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT review_question_review_answer_check CHECK (review_answer IN ('NEGATIVE', 'NEUTRAL', 'POSITIVE')),
    CONSTRAINT review_question_review_question_type_check CHECK (review_question_type IN (
        'PALATABILITY', 'DIGESTION', 'FEEDING_CONVENIENCE', 'SKIN_COAT', 'WEIGHT_VITALITY', 'ALLERGY'
    )),
    CONSTRAINT uk_review_question_review_type UNIQUE (review_id, review_question_type)
);

-- review_recommend
CREATE TABLE review_recommend (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id bigint NOT NULL,
    review_id bigint NOT NULL,
    CONSTRAINT uk_review_recommend_member_review UNIQUE (member_id, review_id)
);

-- review_report
CREATE TABLE review_report (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id bigint NOT NULL,
    reason character varying(255),
    review_id bigint NOT NULL
);

-- product_feedback_check
CREATE TABLE product_feedback_check (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    answered_at timestamp(6) with time zone,
    check_available_at timestamp(6) with time zone,
    check_expires_at timestamp(6) with time zone,
    feedback_check_answer character varying(255),
    feedback_check_status character varying(255) NOT NULL,
    member_id bigint NOT NULL,
    order_product_id bigint NOT NULL,
    pet_id bigint,
    product_id bigint NOT NULL,
    CONSTRAINT product_feedback_check_feedback_check_answer_check CHECK (feedback_check_answer IN ('GOOD', 'NEUTRAL', 'BAD')),
    CONSTRAINT product_feedback_check_feedback_check_status_check CHECK (feedback_check_status IN ('PENDING', 'ANSWERED', 'POSTPONED')),
    CONSTRAINT uk_product_feedback_check_order_product UNIQUE (order_product_id)
);
