-- 이 시점(2026-09-28)까지 ddl-auto: update로 로컬에 쌓인 member_db 스키마를
-- 그대로 캡처한 baseline. Flyway 최초 도입 시 baseline-on-migrate로 처리되므로
-- 기존 데이터가 있는 환경에서는 이 파일이 실제로 실행되지 않고, 완전히 빈 DB에서만
-- 실행되어 스키마를 처음부터 만든다.

-- breed_master
CREATE TABLE breed_master (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    breed_name character varying(255) NOT NULL,
    species character varying(255) NOT NULL,
    CONSTRAINT breed_master_species_check CHECK (species IN ('DOG', 'CAT'))
);

-- concern_master
CREATE TABLE concern_master (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concern_category character varying(255) NOT NULL,
    concern_code character varying(255) NOT NULL,
    species character varying(255) NOT NULL,
    CONSTRAINT concern_master_species_check CHECK (species IN ('DOG', 'CAT'))
);

-- member
CREATE TABLE member (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    auth_id bigint NOT NULL,
    birth date,
    name character varying(255),
    nickname character varying(255) NOT NULL,
    phone character varying(255),
    profile_image character varying(255),
    carrier character varying(255),
    deleted_at timestamp(6) without time zone,
    CONSTRAINT member_carrier_check CHECK (carrier IN ('SKT', 'KT', 'LG_U_PLUS', 'SKT_MVNO', 'KT_MVNO', 'LG_U_PLUS_MVNO')),
    CONSTRAINT uk_member_auth_id UNIQUE (auth_id),
    CONSTRAINT uk_member_nickname UNIQUE (nickname)
);

-- pet
CREATE TABLE pet (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    age integer NOT NULL,
    bcs integer NOT NULL,
    birth_date date,
    breed_id bigint NOT NULL,
    deleted_at timestamp(6) without time zone,
    image character varying(255),
    is_default boolean NOT NULL,
    is_neutered boolean NOT NULL,
    member_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    sex character varying(255) NOT NULL,
    species character varying(255) NOT NULL,
    target_breed_size character varying(255),
    weight double precision NOT NULL,
    CONSTRAINT pet_sex_check CHECK (sex IN ('MALE', 'FEMALE')),
    CONSTRAINT pet_species_check CHECK (species IN ('DOG', 'CAT')),
    CONSTRAINT pet_target_breed_size_check CHECK (target_breed_size IN ('SMALL', 'MEDIUM', 'LARGE'))
);

CREATE UNIQUE INDEX uk_pet_member_default ON pet USING btree (member_id) WHERE (is_default = true);

-- pet_allergy
CREATE TABLE pet_allergy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allergy_code character varying(255) NOT NULL,
    pet_id bigint NOT NULL,
    CONSTRAINT pet_allergy_allergy_code_check CHECK (allergy_code IN (
        'CHICKEN', 'BEEF', 'PORK', 'LAMB', 'DUCK', 'TURKEY', 'RABBIT', 'VENISON', 'GOAT',
        'INSECT', 'KANGAROO', 'FISH', 'SALMON', 'TUNA', 'ANCHOVY', 'CRUSTACEAN', 'BONITO',
        'DAIRY', 'EGG', 'CHEESE', 'WHEY', 'CHOCOLATE', 'GRAPE_RAISIN', 'ONION', 'GARLIC',
        'WHEAT_GLUTEN', 'CORN', 'RICE', 'OAT_BARLEY', 'SOY', 'LENTIL', 'PEA', 'CHICKPEA',
        'POTATO', 'YEAST', 'SWEET_POTATO', 'TAPIOCA', 'OTHER'
    ))
);

-- pet_concern
CREATE TABLE pet_concern (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concern_id bigint NOT NULL,
    pet_id bigint NOT NULL
);

-- address
CREATE TABLE address (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    address character varying(255) NOT NULL,
    address_detail character varying(255) NOT NULL,
    address_name character varying(255) NOT NULL,
    delivery_note character varying(255),
    is_default boolean NOT NULL,
    member_id bigint NOT NULL,
    receiver character varying(255) NOT NULL,
    receiver_phone character varying(255) NOT NULL,
    zip_code character varying(255) NOT NULL
);

-- agreement
CREATE TABLE agreement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreed_at timestamp(6) without time zone NOT NULL,
    agreement_type character varying(255) NOT NULL,
    agreement_version character varying(255) NOT NULL,
    expired_at timestamp(6) without time zone NOT NULL,
    is_agreed boolean NOT NULL,
    member_id bigint NOT NULL,
    CONSTRAINT agreement_agreement_type_check CHECK (agreement_type IN (
        'SERVICE_TERMS', 'PRIVACY_COLLECTION', 'AGE_OVER_14', 'MARKETING_BENEFIT', 'THIRD_PARTY_PROVIDE'
    ))
);

-- wishlist
CREATE TABLE wishlist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    member_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT uk_wishlist_member_product UNIQUE (member_id, product_id)
);
