plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation project(':modules:common-core')
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    testImplementation project(':modules:common-test')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation project(':modules:common-jpa')
    runtimeOnly 'org.postgresql:postgresql'

    // jwt (임시 authId 파싱 - 게이트웨이 검증 방식 확정 전까지, auth-service와 버전 통일)
    implementation 'com.nimbusds:nimbus-jose-jwt:10.9'
}
