spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://${AUTH_SERVICE_HOST:localhost}:8081
              predicates:
                - Path=/api/auth/**
            - id: member-service
              uri: http://${MEMBER_SERVICE_HOST:localhost}:8082
              predicates:
                - Path=/api/members/**
            - id: product-service
              uri: http://${PRODUCT_SERVICE_HOST:localhost}:8083
              predicates:
                - Path=/api/products/**
            - id: order-service
              uri: http://${ORDER_SERVICE_HOST:localhost}:8084
              predicates:
                - Path=/api/orders/**
            - id: payment-service
              uri: http://${PAYMENT_SERVICE_HOST:localhost}:8085
              predicates:
                - Path=/api/payments/**
