spring:
  application:
    name: auth-service
  mvc:
    problemdetails:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          member-service:
            connectTimeout: 1000
            readTimeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
