spring:
  application:
    name: product-service
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
        default_batch_fetch_size: 100

product:
  list:
    default-size: 10
    max-size: 30


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
