-- 이 시점(2026-09-28)까지 ddl-auto: update로 로컬에 쌓인 notification_db 스키마를
-- 그대로 캡처한 baseline. Flyway 최초 도입 시 baseline-on-migrate로 처리되므로
-- 기존 데이터가 있는 환경에서는 이 파일이 실제로 실행되지 않고, 완전히 빈 DB에서만
-- 실행되어 스키마를 처음부터 만든다.

-- fcm_token
CREATE TABLE fcm_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    member_id bigint NOT NULL,
    token character varying(255) NOT NULL,
    CONSTRAINT uk_fcm_token_token UNIQUE (token)
);

-- notification
CREATE TABLE notification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    body character varying(255) NOT NULL,
    member_id bigint NOT NULL,
    read boolean NOT NULL,
    target_id character varying(255),
    target_type character varying(255),
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT notification_target_type_check CHECK (target_type IN ('PRODUCT', 'ORDER', 'TIMEDEAL')),
    CONSTRAINT notification_type_check CHECK (type IN (
        'NOTICE', 'DELIVERY', 'TIMEDEAL', 'STATUS_CHECK', 'RECOMMENDATION', 'RESTOCK'
    ))
);

-- notification_subscription
CREATE TABLE notification_subscription (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    category character varying(255) NOT NULL,
    member_id bigint NOT NULL,
    subscribed boolean NOT NULL,
    CONSTRAINT notification_subscription_category_check CHECK (category = 'TIME_DEAL'),
    CONSTRAINT uk_notification_subscription_member_category UNIQUE (member_id, category)
);

-- time_deal_notification_log
CREATE TABLE time_deal_notification_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id bigint NOT NULL,
    sent_at timestamp(6) with time zone NOT NULL,
    notification_type character varying(255) NOT NULL,
    CONSTRAINT time_deal_notification_log_notification_type_check CHECK (notification_type IN ('UPCOMING', 'START', 'ONGOING')),
    CONSTRAINT uk_time_deal_notification_log_deal_type UNIQUE (deal_id, notification_type)
);
