spring:
  application:
    name: member-service
  mvc:
    problemdetails:
      enabled: true
  jpa:
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            connectTimeout: 1000
            readTimeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
