global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'auth-service:8081'
          - 'member-service:8082'
          - 'product-service:8083'
          - 'order-service:8084'
          - 'payment-service:8085'
          - 'review-service:8086'
