-- 이 시점(2026-09-28)까지 ddl-auto: update로 로컬에 쌓인 auth_db 스키마를
-- 그대로 캡처한 baseline. Flyway 최초 도입 시 baseline-on-migrate로 처리되므로
-- 기존 데이터가 있는 환경에서는 이 파일이 실제로 실행되지 않고, 완전히 빈 DB에서만
-- 실행되어 스키마를 처음부터 만든다.

-- auth
CREATE TABLE auth (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    provider character varying(255) NOT NULL,
    social_email character varying(255),
    social_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT auth_status_check CHECK (status IN ('ACTIVE', 'DELETED')),
    CONSTRAINT ukndaecfh66rrybjh3pvny6e1a0 UNIQUE (provider, social_id)
);
