dependencies {
    api platform('org.testcontainers:testcontainers-bom:1.20.4')

    api 'org.testcontainers:testcontainers'
    api 'org.springframework.boot:spring-boot-test'
    api 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    api 'org.springframework.boot:spring-boot-test-autoconfigure'

    api 'org.testcontainers:junit-jupiter'
    api 'org.testcontainers:postgresql'
    api 'org.testcontainers:mongodb'
    api 'org.testcontainers:kafka'
}
