plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation project(':modules:common-jpa')
    implementation project(':modules:common-storage')
    implementation project(':modules:common-security')

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.0'
    implementation 'org.springframework.kafka:spring-kafka'

    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    testImplementation project(':modules:common-test')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
