plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation project(':modules:common-core')
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    testImplementation project(':modules:common-test')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation project(':modules:common-jpa')
    runtimeOnly 'org.postgresql:postgresql'

    //oauth2
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // spring security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // jwt (RSA 서명/키 처리)
    implementation 'com.nimbusds:nimbus-jose-jwt'
}
